flask1/app/models.py
__author__ = 'luoguoling'
from . import db
class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True)
    password = db.Column(db.String(32),nullable=False)


    def __init__(self, username, password):
        self.username = username
        self.password = password

    def __repr__(self):
        return "<User '{:s}'>".format(self.username)

class Alticle(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    userid = db.Column(db.Integer, nullable=False)
    title = db.Column(db.String(100),nullable=False)
    text = db.Column(db.String(3000),nullable=False)

    def __init__(self,userId,title,text):
        self.userid = userId
        self.title = title
        self.text = text

flask1/app/__init__.py
__author__ = 'luoguoling'
from flask import  Flask
from flask.ext.sqlalchemy import SQLAlchemy
from config import config
db = SQLAlchemy()
def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    db.init_app(app)
    from .main import main as  main_blueprint
    app.register_blueprint(main_blueprint)
    return app

flask1/app/deploylinux/__init__.py
__author__ = 'luoguoling'
from flask import Blueprint
deploylinux = Blueprint('deploylinux',__name__)
from . import views,errors

flask1/app/excommand/__init__.py
__author__ = 'luoguoling'
from flask import Blueprint
excommand = Blueprint('excommand',__name__)
from . import views,errors

flask1/app/main/__init__.py
__author__ = 'luoguoling'
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

flask1/app/main/views.py
__author__ = 'luoguoling'
import os
from flask import Flask, request, session, g, redirect, url_for, abort, render_template, flash
from . import main
from .. import db
from ..models import User,Alticle
@main.route('/')
def show_entries():
    username = session.get('username')
    print username
    return render_template('main/index.html',username=username)
@main.route('/add', methods=['POST'])
def add_entry():
    if not session.get('logged_in'):
        abort(401)
    print request.form['title']
    new_alticlee=Alticle(userId=12,title=request.form['title'],text=request.form['text'])
    db.session.add(new_alticlee)
    db.session.commit()
    flash('New entry was successfully posted')
    return redirect(url_for('main.show_entries'))
@main.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    if request.method == 'POST':
        res=User.query.filter_by(username=request.form['username'],password=request.form['password']).first()
        print res
        if res==None:
            error = 'Invalid username or password11'
        else:
            session['logged_in'] = True
            session['username'] = request.form['username']
            print session['username']
            flash('You were logged in')
            return redirect(url_for('main.show_entries'))
    return render_template('main/login.html', error=error)
@main.route('/logout')
def logout():
    session.pop('logged_in', None)
    flash('You were logged out')
#    return redirect(url_for('main.show_entries'))
    return render_template('main/login.html')

flask1/app/oplog/__init__.py
__author__ = 'luoguoling'
from flask import Blueprint
oplog = Blueprint('oplog',__name__)
from . import views,errors

flask1/app/templates/main/layout.html
<!doctype html>
<title>系统登录</title>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
<div class="page">
  <h1>系统登录</h1>
  <div class="metanav">
  {% if not session.logged_in %}
    <a href="{{ url_for('main.login') }}">log in</a>
  {% else %}
    <a href="{{ url_for('main.logout') }}">log out</a>
  {% endif %}
  </div>
  {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
  {% block body %}{% endblock %}
</div>

flask1/app/templates/main/login.html
{% extends "main/layout.html" %}
{% block body %}
  <h2>Login</h2>
  {% if error %}<p class="error"><strong>Error:</strong> {{ error }}{% endif %}
  <form action="{{ url_for('main.login') }}" method="post">
    <dl>
      <dt>Username:
      <dd><input type="text" name="username">
      <dt>Password:
      <dd><input type="password" name="password">
      <dd><input type="submit" value="Login">
    </dl>
  </form>
{% endblock %}

flask1/app/templates/main/show_entries.html
{% extends "main/layout.html" %}
{% block body %}
  {% if session.logged_in %}
    <form action="{{ url_for('main.add_entry') }}" method="post" class="add-entry">
      <dl>
        <dt>Title:
        <dd><input type="text" size="30" name="title">
        <dt>Text:
        <dd><textarea name="text" rows="5" cols="40"></textarea>
        <dd><input type="submit" value="Share">
      </dl>
    </form>
  {% endif %}
  <ul class="entries">
  {% for entry in entries %}
    <li><h2>{{ entry.title }}</h2>{{ entry.text|safe }}
  {% else %}
    <li><em>Unbelievable.  No entries here so far</em>
  {% endfor %}
  </ul>
{% endblock %}